<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>set Industry input</name>
  <uuid>1dcc1b84-3dbe-4ba3-b79e-8f6d11ae2d4d</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to a new ML model input where the clientindustry is 0 ;
]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
